### ISSUE TITLE
installed and configured but how do I get started?

### ISSUE THREAD

**Issue by 3FanYu** [KevinAst/gitbook-plugin-folding-menu#3]
I've correctly installed and configured the plugin in book.json, but what should I do in my SUMMARY.md to make the plugin works?

**Comment by KevinAst** [comment]
Regarding the installation, simply follow the **Install** instructions _([found here](https://github.com/KevinAst/gitbook-plugin-folding-menu#install))_. Depending on your GitBook environment, there is a 2nd installation step beyond the `book.json` configuration.

There are **no changes** required within any of your markdown.  The plugin simply changes the behavior of your left-nav menu to open one section at a time _(i.e. the active section)_.

**Comment by 3FanYu** [comment]
Sir, first of all thank you for replying. I think I have successfully installed the plugin like shown in the image below, but sill my nav bar is remaining inactive.
<img width="1260" alt="螢幕快照 2019-03-18 上午9 21 43" src="https://user-images.githubusercontent.com/37991957/54501262-551a0480-495f-11e9-82d5-fa9d0bb85c95.png">

**Comment by KevinAst** [comment]
Well your gitbook output looks correct.

Not sure what you mean when you say your **_"nav bar is remaining inactive"_**.  Can you supply a screen shot of your docs page (i.e. http://localhost:4000)?

**Comment by 3FanYu** [comment]
so inside the nav bar, tabs those are supposed to be collapsible won't function at all, not even clickable
<img width="1470" alt="螢幕快照 2019-03-18 上午10 10 25" src="https://user-images.githubusercontent.com/37991957/54502587-4f73ed00-4966-11e9-8c26-6a5fd37f25a0.png">

**Comment by 3FanYu** [comment]
this is my SUMMARY.md, not sure if I've done things incorrectly 
<img width="1083" alt="螢幕快照 2019-03-18 上午10 14 14" src="https://user-images.githubusercontent.com/37991957/54502651-b72a3800-4966-11e9-9849-250bc2df646b.png">

**Comment by KevinAst** [comment]
The reason this is not working is your top-level entries are NOT links.

Because the **folding-menu** plugin initially exposes only your top-level entries, these top-level entries must be linkable for it to work.

Because (in your case) the top-level entries are NOT links, there is nothing to activate them.  The top-level links are what trigger the plugin to expand the sections.

To make this work, simply make your top-level entries link into your document.

Typically, the top-level is a given markdown file, and the sub-links are hash tags into the same file.  In the following example, the given section references the same file (`start.md`):

```
* [Getting Started](start.md)
  * [Install](start.md#install)
  * [Access](start.md#access)
  * [Potential Need for Polyfills](start.md#potential-need-for-polyfills)
```

However this doesn't have the case.  You can reference different files. However the top-level still needs to be a link.  In the following example, the top-level links to a `coreApi.md` and the sub-links follow a `api.md`:

```
* [Core API](coreApi.md)
  * [createFeature()](api.md#createFeature)
  * [expandWithFassets()](api.md#expandWithFassets)
  * [withFassets()](api.md#withFassets)
  * Misc ...
    * [assertNoRootAppElm()](api.md#assertNoRootAppElm)
```

In your case, you have a couple of options:

1. You could create a small top-level markdown file referenced for each section (that simply summarizes the topic).
2. Your top-level link could reference the first sub-topic link
3. etc.

Hope this helps.  Let me know if you get it working.

**Comment by 3FanYu** [comment]
It's working! Thank you sir for your patient guidance, however here is one last question. Is it possible to make the top-levels just to unfold and reveal the sub links when clicked instead of linking to another extra page?

**Comment by KevinAst** [comment]
I think what your asking is for it to initially expand out through the second level.  While this could technically be done (driven say through a `initialLevels` configuration option), it would significantly change the plugin logic.  I **would not be motivated** to work on such an enhancement, because _it is rather an unconventional use case_ :-)

I was trying to think of a way to make the top-level link `clickable` in all cases.  From a plugin perspective, this is not really possible.  The plugin is non-intrusive in that it doesn't alter your gitbook page in any way.  Rather it merely listens for the gitbook `"page.change"` event ... emitted whenever a `file.md` changes within the gitbook framework.  As a result, the document has to emit a top-level event (generated by the link) for this to work.

I briefly played with attempting some sort of work-around in the `SUMMARY.md` top-levels ... for example referencing a self link (`* [Section](#)`) or a link to the root document (`* [Section](intro.md)`), but nothing really worked.

If your interested in looking a more complete example, my **feature-u** open source project has a fairly extensive table-of-contents:

- The documentation site: https://feature-u.js.org/
- The documentation root: https://github.com/KevinAst/feature-u/tree/master/docs
- The table-of-contents: https://raw.githubusercontent.com/KevinAst/feature-u/master/docs/toc.md

Hope this helps.
